name: Create qa promotion pull request
on:
  push:
    branches:
      - dev
jobs:
  argocdSync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ArgoCD Application
        uses: omegion/argocd-actions@master
        with:
          address: "argocd-suxess-it-admin.apps.cluster1.mcp.pitagora.at"
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: "podtato-head-dev"
          
  qaPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: qa
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: qa-promotion
          delete-branch: true
          title: promote dev to qa
          
