name: Create dev promotion pull request
on:
  push:
    branches:
      - main
jobs:
  deprecatedAPIsCheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master
      - name: Check Deprecations in Helm-Chart
        run: |
          helm template . | pluto detect -owide -
  devPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: dev-promotion
          delete-branch: true
          title: promote main to dev

