name: Create production promotion pull request
on:
  push:
    branches:
      - main
jobs:
  devPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for creating Pull Requests
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: main
          target_branch: dev
          title: promote main to dev
          get_diff: true
      

