on:
  push:
    branches:
      - main

jobs:
  create-pull-reqest:
    name: create pull request
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      # no need to do anything here, we just want to create pull request from dev to main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: dev
          branch: main
      

