name: Create prod promotion pull request
on:
  push:
    branches:
      - qa
jobs:
  argocdSync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ArgoCD Application
        uses: omegion/argocd-actions@master
        with:
          address: "argocd-suxess-it-admin.apps.cluster1.mcp.pitagora.at"
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: "podtato-head-qa"
          
  prodPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod
      - name: Reset promotion branch
        run: |
          git fetch origin qa:qa
          git reset --hard qa
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: prod-promotion
          delete-branch: true
          title: promote qa to prod
